language: node_js
node_js:
- '8'
install:
- npm install
- npm install -g nodemon
script:
- npm test
sudo: required
before_deploy:
- zip -r battle.net.zip .
- mkdir -p dpl_cd_upload
- mv battle.net.zip dpl_cd_upload/battle.net.zip
after_deploy:
- npm start
deploy:
- provider: s3
  region: eu-central-1
  access_key_id: AKIAJNFAUHYHJLIATM4A
  secret_access_key: &1
    secure: VMHVCSQPMfVX7KxhnD2YlbDY484w6whzGfaifG1McM8sajY94jxqIY311bEOV74lOfUXz+3VVmufs/i7T5RdlDFLvZas1X0GdNJFhmghHq2WYPCTOIHJw3pnWMTb7Th+n6zjYQHljhGmfAyzeqUu4UtQ5WMTfppbaCmH3+Wj3SgICazE0mzsi1VkpQD4QUPzg+J4e9oOmG9/cFpnPXxwJbCGFwkj1LbWaGEdqnO2nBFNNrO8qseIUQpk9L2bX0BJMP8KbHjeVeS8aiInZRipip8rcBDngQjo5m9M/8LAo9oxE2L5nobivR9yKOefM59ydWqpbezxh5xk9E8MtiuBc/x5PRXV62dWyUYZoJGObR3xdTLoGCU3sdxnA5qCMn/kRXkk1gR9jkGxuqKyjLIzMH4Y09ml6L48zf7wd4qB2+sqSW8A5UhLAL7EfQDkwxlhVaGnJd4jIVb1BekK17msBFvE8xGSUH26UqXKzxm1TAssKGc6OXgMvv+07HrLmYlkJs/9QkG7k+f2qrCVOtip/yzyBIWemJ+doUkfN7PYbekBcpEbarGcSlUCdutsVyOB/y8MbS5/3dS+XDW7TpMxmDk+r6/cSZDl8/BIRQttbT7XqT6Bl6iVURvvxhIhWi9+FYT16AOgevoNdMBOTg6Gdq5Xe7E3l2w6GtZ7GEm1yqw=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: Bradawk/insset-devops
  bucket: aws-bucket-brad-niepceron
- provider: codedeploy
  region: eu-central-1
  access_key_id: AKIAJNFAUHYHJLIATM4A
  secret_access_key: *1
  bucket: aws-bucket-brad-niepceron
  key: battle.net.zip
  bundle_type: zip
  application: insset-devops
  deployment_group: BradDeploymentGroup
  on: *2