language: node_js
node_js:
- iojs
- '8'
install:
- npm install
script:
- npm test
after_success: zip -r battle.net.zip .
before_deploy:
- mkdir -p dpl_cd_upload
- mv battle.net.zip dpl_cd_upload/battle.net.zip